// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAftKIWH2K08y_bTFlbGM7SeueWJyfKkQo',
    appId: '1:82801091027:web:366d874bca168ff32e4f26',
    messagingSenderId: '82801091027',
    projectId: 'faculty-app-ee827',
    authDomain: 'faculty-app-ee827.firebaseapp.com',
    storageBucket: 'faculty-app-ee827.firebasestorage.app',
    measurementId: 'G-VX04W6MXS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbSgjOqMNW3tFxi0txLjKpAFW1pk0t7go',
    appId: '1:82801091027:android:3e8cab95d68088592e4f26',
    messagingSenderId: '82801091027',
    projectId: 'faculty-app-ee827',
    storageBucket: 'faculty-app-ee827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCukF370ms6WCFqTghqGo942IBH-GPZ4uI',
    appId: '1:82801091027:ios:2e0c434b0a2391cd2e4f26',
    messagingSenderId: '82801091027',
    projectId: 'faculty-app-ee827',
    storageBucket: 'faculty-app-ee827.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCukF370ms6WCFqTghqGo942IBH-GPZ4uI',
    appId: '1:82801091027:ios:2e0c434b0a2391cd2e4f26',
    messagingSenderId: '82801091027',
    projectId: 'faculty-app-ee827',
    storageBucket: 'faculty-app-ee827.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAftKIWH2K08y_bTFlbGM7SeueWJyfKkQo',
    appId: '1:82801091027:web:332be5d491b8456b2e4f26',
    messagingSenderId: '82801091027',
    projectId: 'faculty-app-ee827',
    authDomain: 'faculty-app-ee827.firebaseapp.com',
    storageBucket: 'faculty-app-ee827.firebasestorage.app',
    measurementId: 'G-YJ1MH8TYWC',
  );
}
